//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.DataAccess {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataAccess.IBugAccessService")]
    public interface IBugAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBugAccessService/GetBugs", ReplyAction="http://tempuri.org/IBugAccessService/GetBugsResponse")]
        BugAccessLibrary.Entities.Bug[] GetBugs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBugAccessService/GetBugs", ReplyAction="http://tempuri.org/IBugAccessService/GetBugsResponse")]
        System.Threading.Tasks.Task<BugAccessLibrary.Entities.Bug[]> GetBugsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBugAccessService/GetTest", ReplyAction="http://tempuri.org/IBugAccessService/GetTestResponse")]
        int GetTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBugAccessService/GetTest", ReplyAction="http://tempuri.org/IBugAccessService/GetTestResponse")]
        System.Threading.Tasks.Task<int> GetTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBugAccessService/GetData", ReplyAction="http://tempuri.org/IBugAccessService/GetDataResponse")]
        BugAccessLibrary.Data GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBugAccessService/GetData", ReplyAction="http://tempuri.org/IBugAccessService/GetDataResponse")]
        System.Threading.Tasks.Task<BugAccessLibrary.Data> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBugAccessServiceChannel : test.DataAccess.IBugAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BugAccessServiceClient : System.ServiceModel.ClientBase<test.DataAccess.IBugAccessService>, test.DataAccess.IBugAccessService {
        
        public BugAccessServiceClient() {
        }
        
        public BugAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BugAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BugAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BugAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BugAccessLibrary.Entities.Bug[] GetBugs() {
            return base.Channel.GetBugs();
        }
        
        public System.Threading.Tasks.Task<BugAccessLibrary.Entities.Bug[]> GetBugsAsync() {
            return base.Channel.GetBugsAsync();
        }
        
        public int GetTest() {
            return base.Channel.GetTest();
        }
        
        public System.Threading.Tasks.Task<int> GetTestAsync() {
            return base.Channel.GetTestAsync();
        }
        
        public BugAccessLibrary.Data GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<BugAccessLibrary.Data> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
