//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DataAccessService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bug", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    [System.SerializableAttribute()]
    public partial class Bug : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.Component ComponentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.Employee FixerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.BugPriority PrioriryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.Project ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.Employee RepoterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.BugSeverity SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Build {
            get {
                return this.BuildField;
            }
            set {
                if ((this.BuildField.Equals(value) != true)) {
                    this.BuildField = value;
                    this.RaisePropertyChanged("Build");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.Component Component {
            get {
                return this.ComponentField;
            }
            set {
                if ((this.ComponentField.Equals(value) != true)) {
                    this.ComponentField = value;
                    this.RaisePropertyChanged("Component");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.Employee Fixer {
            get {
                return this.FixerField;
            }
            set {
                if ((object.ReferenceEquals(this.FixerField, value) != true)) {
                    this.FixerField = value;
                    this.RaisePropertyChanged("Fixer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.BugPriority Prioriry {
            get {
                return this.PrioriryField;
            }
            set {
                if ((this.PrioriryField.Equals(value) != true)) {
                    this.PrioriryField = value;
                    this.RaisePropertyChanged("Prioriry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.Project Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.Employee Repoter {
            get {
                return this.RepoterField;
            }
            set {
                if ((object.ReferenceEquals(this.RepoterField, value) != true)) {
                    this.RepoterField = value;
                    this.RaisePropertyChanged("Repoter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.BugSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI.DataAccessService.EmployeePosition PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI.DataAccessService.EmployeePosition Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurName {
            get {
                return this.SurNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurNameField, value) != true)) {
                    this.SurNameField = value;
                    this.RaisePropertyChanged("SurName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Component", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    public enum Component : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONFIG = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        API = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMPONENT = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BugPriority", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    public enum BugPriority : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BugSeverity", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    public enum BugSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Critical = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Major = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FeatureRequest = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reopened = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verifield = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unconfirmed = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeePosition", Namespace="http://schemas.datacontract.org/2004/07/BugAccessLibrary.Entities")]
    public enum EmployeePosition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jun = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Middle = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lead = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boss = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataAccessService.IBugAccessService")]
    public interface IBugAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBugAccessService/GetBugs", ReplyAction="http://tempuri.org/IBugAccessService/GetBugsResponse")]
        UI.DataAccessService.Bug[] GetBugs();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBugAccessService/GetBugs", ReplyAction="http://tempuri.org/IBugAccessService/GetBugsResponse")]
        System.IAsyncResult BeginGetBugs(System.AsyncCallback callback, object asyncState);
        
        UI.DataAccessService.Bug[] EndGetBugs(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBugAccessServiceChannel : UI.DataAccessService.IBugAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBugsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBugsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UI.DataAccessService.Bug[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UI.DataAccessService.Bug[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BugAccessServiceClient : System.ServiceModel.ClientBase<UI.DataAccessService.IBugAccessService>, UI.DataAccessService.IBugAccessService {
        
        private BeginOperationDelegate onBeginGetBugsDelegate;
        
        private EndOperationDelegate onEndGetBugsDelegate;
        
        private System.Threading.SendOrPostCallback onGetBugsCompletedDelegate;
        
        public BugAccessServiceClient() {
        }
        
        public BugAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BugAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BugAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BugAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetBugsCompletedEventArgs> GetBugsCompleted;
        
        public UI.DataAccessService.Bug[] GetBugs() {
            return base.Channel.GetBugs();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetBugs(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBugs(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public UI.DataAccessService.Bug[] EndGetBugs(System.IAsyncResult result) {
            return base.Channel.EndGetBugs(result);
        }
        
        private System.IAsyncResult OnBeginGetBugs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetBugs(callback, asyncState);
        }
        
        private object[] OnEndGetBugs(System.IAsyncResult result) {
            UI.DataAccessService.Bug[] retVal = this.EndGetBugs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBugsCompleted(object state) {
            if ((this.GetBugsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBugsCompleted(this, new GetBugsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBugsAsync() {
            this.GetBugsAsync(null);
        }
        
        public void GetBugsAsync(object userState) {
            if ((this.onBeginGetBugsDelegate == null)) {
                this.onBeginGetBugsDelegate = new BeginOperationDelegate(this.OnBeginGetBugs);
            }
            if ((this.onEndGetBugsDelegate == null)) {
                this.onEndGetBugsDelegate = new EndOperationDelegate(this.OnEndGetBugs);
            }
            if ((this.onGetBugsCompletedDelegate == null)) {
                this.onGetBugsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBugsCompleted);
            }
            base.InvokeAsync(this.onBeginGetBugsDelegate, null, this.onEndGetBugsDelegate, this.onGetBugsCompletedDelegate, userState);
        }
    }
}
